// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/pod.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_pod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_pod_proto_rawDescGZIP(), []int{0}
}

type PodId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodId) Reset() {
	*x = PodId{}
	mi := &file_proto_pod_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodId) ProtoMessage() {}

func (x *PodId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodId.ProtoReflect.Descriptor instead.
func (*PodId) Descriptor() ([]byte, []int) {
	return file_proto_pod_proto_rawDescGZIP(), []int{1}
}

func (x *PodId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PodEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // ADDED, MODIFIED, DELETED
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Position      []float64              `protobuf:"fixed64,6,rep,packed,name=position,proto3" json:"position,omitempty"`
	Hp            int32                  `protobuf:"varint,7,opt,name=hp,proto3" json:"hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodEvent) Reset() {
	*x = PodEvent{}
	mi := &file_proto_pod_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodEvent) ProtoMessage() {}

func (x *PodEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodEvent.ProtoReflect.Descriptor instead.
func (*PodEvent) Descriptor() ([]byte, []int) {
	return file_proto_pod_proto_rawDescGZIP(), []int{2}
}

func (x *PodEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PodEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PodEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PodEvent) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PodEvent) GetPosition() []float64 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PodEvent) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_proto_pod_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_pod_proto_rawDescGZIP(), []int{3}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_pod_proto protoreflect.FileDescriptor

const file_proto_pod_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/pod.proto\x12\x03pod\"\a\n" +
	"\x05Empty\"\x17\n" +
	"\x05PodId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x96\x01\n" +
	"\bPodEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12\x1a\n" +
	"\bposition\x18\x06 \x03(\x01R\bposition\x12\x0e\n" +
	"\x02hp\x18\a \x01(\x05R\x02hp\"D\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2d\n" +
	"\n" +
	"PodService\x12(\n" +
	"\tSubscribe\x12\n" +
	".pod.Empty\x1a\r.pod.PodEvent0\x01\x12,\n" +
	"\tDeletePod\x12\n" +
	".pod.PodId\x1a\x13.pod.ActionResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_pod_proto_rawDescOnce sync.Once
	file_proto_pod_proto_rawDescData []byte
)

func file_proto_pod_proto_rawDescGZIP() []byte {
	file_proto_pod_proto_rawDescOnce.Do(func() {
		file_proto_pod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pod_proto_rawDesc), len(file_proto_pod_proto_rawDesc)))
	})
	return file_proto_pod_proto_rawDescData
}

var file_proto_pod_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_pod_proto_goTypes = []any{
	(*Empty)(nil),          // 0: pod.Empty
	(*PodId)(nil),          // 1: pod.PodId
	(*PodEvent)(nil),       // 2: pod.PodEvent
	(*ActionResponse)(nil), // 3: pod.ActionResponse
}
var file_proto_pod_proto_depIdxs = []int32{
	0, // 0: pod.PodService.Subscribe:input_type -> pod.Empty
	1, // 1: pod.PodService.DeletePod:input_type -> pod.PodId
	2, // 2: pod.PodService.Subscribe:output_type -> pod.PodEvent
	3, // 3: pod.PodService.DeletePod:output_type -> pod.ActionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pod_proto_init() }
func file_proto_pod_proto_init() {
	if File_proto_pod_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pod_proto_rawDesc), len(file_proto_pod_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pod_proto_goTypes,
		DependencyIndexes: file_proto_pod_proto_depIdxs,
		MessageInfos:      file_proto_pod_proto_msgTypes,
	}.Build()
	File_proto_pod_proto = out.File
	file_proto_pod_proto_goTypes = nil
	file_proto_pod_proto_depIdxs = nil
}
